name: Build Release

on: 
  push:
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'

      - name: Get tag
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}

      - name: Run unit tests
        run: go test ./...

      - name: Build code
        run: go build

      - name: Zip binary
        run: zip asset-fetcher_${{ env.TAG }} asset-fetcher
        env:
          TAG: ${{ steps.get_tag.outputs.TAG }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ steps.get_tag.outputs.TAG }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./asset-fetcher_${{ env.TAG }}.zip
          asset_name: my-artifact_${{ env.TAG }}.zip
          asset_content_type: application/zip
